version: '3.8'
services:
  main:
    build: .
    volumes:
      - ./bot:/usr/src/bot:rw
    environment:
      - TOKEN=${TOKEN}
      - GUILDS=${GUILDS}
    tty: true
    command: ["python3", "main.py"]
    restart: always
